---
apiVersion: apps/v1 # specifies the API version for the Deployment resource
kind: Deployment # defines the type of Kubernetes resource being created
metadata:
  name: my-web-app # the name of the deployment to identify this deployment resource
  labels:
    app: web # key-value pairs that can be used to organize and select resources
spec: # defines the desired state for the deployment
  replicas: 3 # specifies that 3 replicas (pods) of the application should be running
  selector:
    matchLabels:
      app: web # criteria for selecting the pods that this deployment will manage (it selects pods with the label app: web)
  template: # describes the pods that will be created by the deployment
    metadata:
      labels:
        app: web # labels assigned to the pods created by this deployment (must match the selector labels)
    spec: # defines the specification for the pod template
      containers: # lists the containers that will be running inside the pods
        - name: web # the name of the container
          image: nginx:latest # the Docker image used for this container
          ports:
            - containerPort: 80 # specifies that port 80 should be exposed on the container

---
apiVersion: v1 # specifies the API version for the Service resource
kind: Service
metadata:
  name: my-web-app-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer